Removed test_has_many_with_primary_key method that wasn't being used because another method by the same name was defined below it. (I tried simply renaming it, but it fails with: NoMethodError: undefined method `reading' for #<Membership user_id: 1, group_id: 1>)